# Generated by Django 3.0.1 on 2019-12-31 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_board_boardword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardword',
            old_name='color',
            new_name='classification',
        ),
        migrations.AddField(
            model_name='boardword',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
