# Generated by Django 3.0.1 on 2020-01-03 22:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20191231_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
